name: Rename Package Folder

on:
  workflow_dispatch:

  jobs:
    rename:
        runs-on: ubuntu-latest
            steps:
                  - uses: actions/checkout@v3

                        - name: Rename package folder
                                run: |
                                          mkdir -p app/src/main/kotlin/com/secretdialer/app
                                                    cp -r app/src/main/kotlin/org/fossify/phone/. app/src/main/kotlin/com/secretdialer/app/
                                                              rm -rf app/src/main/kotlin/org

                                                                    - name: Commit changes
                                                                            run: |
                                                                                      git config user.email "action@github.com"
                                                                                                git config user.name "GitHub Action"
                                                                                                          git add .
                                                                                                                    git commit -m "refactor: rename package folder structure"
                                                                                                                              git push